### ISSUE TITLE
git-remote-hg fails to detect case changes on MacOS

### ISSUE THREAD

**Issue by joerivanruth** [mnauw/git-remote-hg#14]
For example, if the repository contains a file foo.txt which used to be named Foo.txt, Git will still create Foo.txt. I assume this is caused by the Mac filesystem being case insensitive by default.

It would be desirable for the git history to be identical regardless of the tool having run on Linux or MacOS.

Here's a demo shell script:

```
#!/bin/sh

set -e -x

if [ ! -x bin/git-remote-hg ]; then
    mkdir -p bin
    wget https://raw.github.com/mnauw/git-remote-hg/master/git-remote-hg -O bin/git-remote-hg
    chmod +x bin/git-remote-hg
fi
PATH="$PWD/bin:$PATH"

rm -rf hg_repo git_repo

mkdir hg_repo
cd hg_repo
hg init

echo 1 >Foo.txt
hg add Foo.txt
hg commit -m "Create Foo.txt"

hg mv Foo.txt dummy
hg mv dummy foo.txt
hg commit -m "Move Foo.txt to foo.txt"

echo 2 >foo.txt
hg commit -m "Modify foo.txt"

cd ..
git clone hg::file://$PWD/hg_repo git_repo

# git_repo should contain Foo.txt, not foo.txt
ls git_repo | fgrep foo.txt
```

**Comment by mnauw** [comment]
This behavior is not specific to `git-remote-hg`, but is generic for Git on MacOS (due to the case issue), including the `git-fast-import` and `git-fast-export` tools that are relied upon.  In particular, if in the above script the `git clone` line is changed to the following, the resulting repo contains an appropriately renamed `foo.txt`:
```
git clone -c core.ignoreCase=false hg::file://$PWD/hg_repo git_repo
```
Note that `core.ignoreCase` is likely set to true on MacOS, unlike the otherwise default false.

**Comment by joerivanruth** [comment]
Thanks! I am really happy to learn about `core.ignoreCase`.

I did notice that after running `git clone -c core.ignorecase=false`, I still had to run `git config core.ignorecase false` in the resulting repo but that's not a major problem. And probably not something that can be helped by git-remote-hg. 

Thanks,

Joeri
