### ISSUE TITLE
Idea: repair corrupt marks

### ISSUE THREAD

**Issue by novalis** [mnauw/git-remote-hg#15]
As we've seen in the past (e.g. https://github.com/felipec/git-remote-hg/issues/4), sometimes the marks get out-of-sync between git and hg.  One way that this can happen (I think) is if commits are stripped on the hg side.  We've experienced this repeatedly internally; unfortunately, all of our repos are proprietary, and at any rate, we don't get copies of those repos until *after* the issue has already caused fast-import to crash.  I propose that (configurably) before git-remote-hg starts work, it should open up the git and hg marks files and delete any marks which are missing from either side.  I'm happy to write this code (indeed, I already have an internal version of it that's about to go into testing, based on felipec's Ruby script).  But before I clean up my work for upstreaming, I want to know if such a patch is likely to be accepted.

Does this seem like a good idea to you?

Thanks.

cc @abliss

**Comment by mnauw** [comment]
This can indeed (commonly) happen if some form of garbage collection on dangling commits happens on either side.  For that reason the `git-hg-helper` has a gc subcommand to help with this, see e.g. https://github.com/mnauw/git-remote-hg/blob/master/git-hg-helper#L376

As such, it indeed makes sense to have some cleanup helper, but what you propose might already be covered by `git-hg-helper`?  In any case, one could optionally/configurably make it run automagically, though preferably not unconditionally, since it might entail some processing that is not always desirable.

**Comment by mnauw** [comment]
So I am assuming the proposed is covered by `git-hg-helper` and closing.

Fee free to re-open with additional info.

**Comment by felipec** [comment]
This should really be fixed in Git's core.

What version of Git are you running? I believe Git v2.9 had some fixes for this.
