### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'  when doing "git clone hg::..." with mercurial 5.0

### ISSUE THREAD

**Issue by mbdevpl** [mnauw/git-remote-hg#26]
OS: Ubuntu 18.04
git version: 2.17.1
Mercurial version: 5.0
git-remote-hg: 1.0.1

While cloning an open-source repo:
```
$ git clone hg::ssh://hg@bitbucket.org/takluyver/greentreesnakes
Cloning into 'greentreesnakes'...
requesting all changes
adding changesets
adding manifests
adding file changes
added 63 changesets with 73 changes to 16 files
new changesets 40df06a42a64:16e8d3ce9a18
progress revision walk 'bookmarks/master' (62/62)
progress revision 0 'master' (0/63)
Traceback (most recent call last):
  File "/home/mateusz/Software/git-remote-hg/git-remote-hg", line 1802, in <module>
    sys.exit(main(sys.argv))
  File "/home/mateusz/Software/git-remote-hg/git-remote-hg", line 1783, in main
    do_import(parser)
  File "/home/mateusz/Software/git-remote-hg/git-remote-hg", line 789, in do_import
    export_branch(repo, branch)
  File "/home/mateusz/Software/git-remote-hg/git-remote-hg", line 647, in export_branch
    export_ref(repo, branch, 'branches', head)
  File "/home/mateusz/Software/git-remote-hg/git-remote-hg", line 542, in export_ref
    revs = revwalk(repo, ename, head)
  File "/home/mateusz/Software/git-remote-hg/git-remote-hg", line 520, in revwalk
    interval = b.rev() / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
fatal: stream ends early
fast-import: dumping crash report to /home/mateusz/Projects/greentreesnakes/.git/fast_import_crash_5633
fatal: Error while running fast-import
```

Maybe the fix could be as simple as:
```
interval = b.rev() / 10 if b.rev() is not None else ...
```
but as I'm not familiar with Mercurial I have no idea what a good default value would be in this case. Also, haven't tried other repos yet.

**Comment by mbdevpl** [comment]
Doing `git config --global remote-hg.track-branches false` resolves the issue, although I'm not sure why. Could it be because of the branch names (output from https://bitbucket.org/takluyver/greentreesnakes/branches/?status=all) like below:
```
_________bc/add-astconstant-and-py38-deprecations-1547721692498
mdartiailh/specify-the-type-of-is_async-in-comprehe-1530636897580
ajankit2304/documentation-for-node-classdef-modified-1497432790015
graingert/fix-note-for-formattedvalue-conversion-a-1496667658167
```
? They look pretty usual...

**Comment by mnauw** [comment]
Unfortunately 'usual' is always a bit relative and a matter of a system's taste ;-)  In this case, the problem is in the `_________` part.  To elaborate, there is a translation back and forth from (e.g.) hg branch name to git branch name, since the ` ` (space) character is invalid in git branch name (although not quite so documented).  This translation is a pretty basic hack; ` ` is replaced to`___` and conversely `___` is replaced back to ` `.  So a problem arises if `___` occurs in (original) hg branch name (as is the case here), since it is then interpreted as a ` ` in the "hg branch namespace" (which is then not found and so on).

This is all a bit tricky, in particular considering backwards compatibility.  All in all, the basic hack seems to have worked so far, so the simplest solution is to replace (hg) `___` into a-very-unlikely-to-occur sequence in git namespace and translate that back to (hg) `___`.  Your guess is as good as mine for the a-very-unlikely-to-occur part, but I picked `%5F%5F%5F` (as a hacked percent-encoding).  In this case, that then leads to a git side of:

`remotes/origin/branches/%5F%5F%5F%5F%5F%5F%5F%5F%5Fbc/add-astconstant-and-py38-deprecations-1547721692498`

**Comment by mbdevpl** [comment]
I see. Thank you for the detailed explanation!
