### ISSUE TITLE
Python3 compatability

### ISSUE THREAD

**Issue by catskul** [mnauw/git-remote-hg#27]
git-remote-hg 1.0.1 installed via pip3 appears to use prints without parenthesis causing 

```
$  git-remote-hg
  File "/home/catskul/.local/bin/git-remote-hg", line 311
    print "blob"
               ^
SyntaxError: Missing parentheses in call to 'print'
```
Looking at the head of the file in question shows indeed it's requesting python3 as the interpreter

```
$  head /home/catskul/.local/bin/git-remote-hg
#!/usr/bin/python3
#
# Copyright (c) 2012 Felipe Contreras
# Copyright (c) 2016 Mark Nauwelaerts
#
```

However the repo shows python2 in at tag 1.0.1:

https://github.com/mnauw/git-remote-hg/blob/v1.0.1/git-remote-hg

```
#!/usr/bin/env python2
#
# Copyright (c) 2012 Felipe Contreras
# Copyright (c) 2016 Mark Nauwelaerts
#
```
Not sure if pip3 did the change?? or if the setup scripts do. If it's not python3 compatible and it's possible, pip3 installation should be prevented.

Beyond the issues with pep3, python3 compatibility would itself be desirable.

**Comment by mnauw** [comment]
It is indeed pip3 that did the change.  It is not only `git-remote-hg` that is not (yet) python3 compatible, but likewise (borderline) so for Mercurial.  There does not seem to be an evident way (that I am aware of at the moment) to dissuade pip3 from being so zealous, so this will resolve (in time) when python3 compatibility is ok ...

**Comment by realnc** [comment]
I maintain the git-remote-hg Gentoo package. Python2-only software will be removed soon-ish (because Python 2 itself will be removed.) This will probably also happen in other distros at some point.

Any ETA on switching to python 3?

**Comment by mnauw** [comment]
Unfortunately, I don't really have an ETA on that.  And more generally, it has been a while I have worked on this project.  More precisely, not since the forked repo's author returned on the scene in June last year.  While I had hoped that return would have allowed for a "merge" of efforts done here in that time, it sadly turned into a lot of commenting (if not ranting) and instead of fast-forwarding the original repo and then take it from there, a bunch of different-but-maybe similar commits were added instead (along with some cherrry-picking).  That (reinventing-the-wheel) effort apparently lasted for only a few weeks, but did enough to make a mess of things.

Suffice to say I am not really interested in any "competition" or "parallel development" and would have preferred to see a more constructive approach.  I do not know (nor anyone else likely) whether the other original repo will see any more activity.  I also have no idea which of the 2 repos is actually (mostly) being used (by distros, users).  If it turns out worthwhile to do so, I might come around to spend a bit more time again in the coming months.

Perhaps the above thoughts/comments are somewhat out-of-scope for this particular issue.  Nevertheless it describes the situation as it is (affecting a.o. this issue).

**Comment by mnauw** [comment]
Continuing the above explanation ... I found some time to merge changes from 'upstream'.
Moreover, python2/3 compatibility has now been committed and should work properly.  Of course, some additional testing and/or feedback is also welcome.  Barring problems, this can then be considered settled and will make a release (in a few weeks).

**Comment by kutsurak** [comment]
I will try these changes (next week probably) and report any problems I might encounter. Thank you very much for your work @mnauw!

**Comment by mnauw** [comment]
No news is good news ;-) so I am considering this OK and have made a new release.
Reports to the contrary can still be presented ...

**Comment by realnc** [comment]
Thanks for your efforts. Unfortunately, Gentoo has already cleaned-up most Python 2 stuff and thus this package is no longer available.

**Comment by mnauw** [comment]
As this package is now python3 enabled, perhaps they can be persuaded to unclean and re-instate.
Alternatively, it is available on PyPI (as python package).
