### ISSUE TITLE
git fetch fails with "error: fast-import died of signal 9"

### ISSUE THREAD

**Issue by dliessi** [mnauw/git-remote-hg#35]
`git clone hg::http://hg.code.sf.net/p/mrbs/hg-code` succeeds.
Then `git fetch` inside the cloned repository fails with
```
no changes found
error: fast-import died of signal 9
fatal: error while running fast-import
```

Mercurial 5.5.2, Python 3.8.6, Git 2.29.2 on macOS 10.13.6

**Comment by dliessi** [comment]
The same happens in Fedora 33 with Mercurial 5.4 (mercurial-py3), Python 3.9.0, Git 2.28.0.

**Comment by mnauw** [comment]
The common denominator and cause here turns out to be git.  A bug has been introduced in git-fast-import handling, specifically in following commit: https://github.com/git/git/commit/ddddf8d7e2.  It is still possible to perform a clone, but upon incremental fetch it fails to read the so-called marks file (which is not yet around for the initial clone).  So the last safe/working git version in this regard seems to be v2.25.1.

I have an easy patch, the hard part now is getting it submitted properly ...

**Comment by mnauw** [comment]
Looks like I may not have to get my fix submitted, since the problem has been discovered recently in upstream git as well and has been fixed in https://github.com/git/git/commit/3f018ec716292b4d757385686f42f57af3bca685.  It looks like that did not make it into a release yet (but that will then at least be after v2.29.2).
