### ISSUE TITLE
Cannot use .hgrc file

### ISSUE THREAD

**Issue by jacobfike** [mnauw/git-remote-hg#5]
When trying to clone a mercurial repo using this tool (by following the instructions and running: `git clone hg::https://REPO_NAME`) I am getting an error about the repository using the largefiles extension.  I have prepared `~/.hgrc` with the appropriate settings for cloning the repo using mercurial itself, but this files doesn't seem to get used by the `git-remote-hg` script.

Can this be fixed?  Or is there a way to pass configuration to the `hg` process when invoked by git?

**Comment by mnauw** [comment]
I tested this with some toy repo using largefiles extension and cloning that one worked ok.  So, is the repo in question a public one?  What version of mercurial is being used?

Another word of caution or warning though.  Even if cloning works out ok (as in my toy case), the result will probably not really look as expected.  That is (as you may or may not know already), the largefiles extension uses so-called standin files stored in a `.hglf` subdirectory which are version-controlled in the usual way.  Their contents is a hash (of the actual content) which is used to locate the real file (content) in a "central store".  Since hg extensions kind of hook/override the high level user commands (such as `push`, `update`) the extension can perform the necessary tricks and book-keeping to ensure the real file (is downloaded and) ends up in desired location, or is properly uploaded (and hash in standin file is updated).  Long story short, as all that is done as part of the native hg high level user commands, using `git-remote-hg` will only result in the standin files in `.hglf` (exactly representing the versioned repository contents).

It would then take some additional steps to end up with the real files.  Such helper support could be added to the `git-hg-helper` script (similar to how it aids a hg subrepo workflow).  That, however, involves appropriately enlisting the extension's codebase and will take some figuring out ...

**Comment by berenm** [comment]
I believe https://github.com/mnauw/git-remote-hg/pull/8 should fix the issue about .hgrc not being used (not the other issue about the largefiles that won't work).
